### ISSUE TITLE
This is great! But, I have a few problems.

### ISSUE THREAD

**Issue by hg0428** [robashton/camera#6]
Adding this library completely changes my game, 0,0 is at the middle, and everything is either scaled up or scaled down depending on the screen size. Also, I would like to be able to rotate the camera.

I would like to see these things fixed.

**Comment by robashton** [comment]
Those are intentional features of this library - if you don't want them, then don't use it (feel free to rip the useful bits of the code). 

I'm not maintaining this library because I don't write JS any more - but it would be trivial enough to add rotation and apply that to the transforms pre/post render.
